### ISSUE TITLE
[question] On 'why would you use' section

### ISSUE THREAD

**Issue by jondot** [facebookexperimental/JSCaml#1]
Is startup speed a motivator? (I know for me it is, question is does JSCaml provide a better experience over running a script in node.js)

**Comment by hermanventer** [comment]
Yes, startup speed is a big part of this. Once you remove the need to scan, parse, lower and JIT on the device, you have a big advantage over a generic JavaScript engine. On the other hand, if you have long running compute intensive code, an optimizing JIT will probably do much better after running for a while.

**Comment by jondot** [comment]
Thanks! it might be worth to list it in the read me. Some of us still care about startup time in CLI tools :)
